config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :cars do
    resources :rentals, only: :create
  end

  get "/dashboard", to: "pages#dashboard"

  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "pages#home"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/car.rb
class Car < ApplicationRecord
  belongs_to :user
  has_one_attached :photo
end

app/models/rental.rb
class Rental < ApplicationRecord
  belongs_to :user
  belongs_to :car
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :rentals
  has_many :cars
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :phone_number])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :phone_number])
  end
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  def index
    @cars = Car.all
    @car = Car.new
  end

  def show
    @car = Car.find(params[:id])
    @rental = Rental.new
  end

  def new
    @car = Car.new
  end

  def create
    @car = Car.new(car_params)
    @car.user = current_user
    if @car.save
      redirect_to cars_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def car_params
    params.require(:car).permit(:name, :car_type, :transmission, :price, :car_description, :photo)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
  end

  def dashboard
    @user = current_user
    @rentals = @user.rentals
    @cars = @user.cars
  end
end

app/controllers/rentals_controller.rb
class RentalsController < ApplicationController
  def new
    @car = Car.find(params[:car_id])
    @rental = Rental.new
  end

  def create
    @car = Car.find(params[:car_id])
    @rental = Rental.new(rental_params)
    @rental.user = current_user
    @rental.car = @car

    if @rental.save
      redirect_to @car, notice: 'Booking successful!'
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def rental_params
    params.require(:rental).permit(:start_date, :end_date)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/cars/index.html.erb
<h1>All Cars</h1>

<ul>
  <div class='cars'>
    <% @cars.each do |car| %>
      <%= link_to car_path(car) do %>
        <div class="car">
          <% if car.photo.attached? %>
            <%= cl_image_tag car.photo.key, height: 150, width: 220, crop: :fill, class: "car-image" %>
           <% else  %>
            <%= image_tag 'city-life_.jpeg', class: "car_image" %>
           <% end %>
          <ul>
              <li><%= car.name %></li>
              <li><%= car.car_type %></li>
              <li>£<%= car.price %></li>
              <li><%= car.transmission %></li>
          </ul>
        </div>
      <% end %>
    <% end %>
  </div>
</ul>

app/views/cars/new.html.erb
<%# <h1>List your car</h1>
<%# here goes your simple form %>
<%# <%= simple_form_for(@car) do |f| %>
  <%# <%= f.input :name %>
  <%# <%= f.input :car_type %>
  <%# <%= f.input :transmission %>
  <%# <%= f.input :price %>
  <%# <%= f.input :car_description %>
  <%# <%= f.submit %>
<%# <% end %>

<div class="container mt-5">
  <div class="row justify-content-center">

    <div class="col-6">
      <h1 class="mb-4">List Your Car</h1>
      <%= simple_form_for(@car, html: { class: 'form' }) do |f| %>
        <div class="form-group">
          <%= f.label :name %>
          <%= f.text_field :name, class: 'form-control' %>
        </div>

        <div class="form-group">
          <%= f.label :car_type %>
          <%= f.select :car_type, options_for_select(['Saloon', 'SUV', 'Hatchback', 'Sedan']), { include_blank: true }, class: 'form-control' %>
        </div>

        <div class="form-group">
          <%= f.label :transmission %>
          <%= f.select :transmission, options_for_select(['Manual', 'Automatic']), { include_blank: true }, class: 'form-control' %>
        </div>

        <div class="form-group">
          <%= f.label :price %>
          <%= f.number_field :price, class: 'form-control' %>
        </div>

        <div class="form-group">
          <%= f.label :car_description %>
          <%= f.text_area :car_description, class: 'form-control', rows: 5 %>
        <div>

        <%= f.input :photo, as: :file %>
        <%= f.submit 'Rent Your Car', class: 'btn btn-primary' %>
      <% end %>
    </div>
  </div>
</div>

app/views/cars/show.html.erb
<div class="car-details">
  <h1><%= @car.name %></h1>
  <div class="car-info d-flex justify-content-around">
  <div class="d-flex align-items-center">
   <div>
    <% if @car.photo.attached? %>
      <%= cl_image_tag @car.photo.key, height: 600, width: 1000, crop: :fill %>
     <% else %>
     <%= image_tag 'city-life_.jpeg', class: "car_image_show" %>
    <% end %>
   </div>
    <div class="mx-5">
     <p><strong>Car Type:</strong> <%= @car.car_type %></p>
     <p><strong>Trasmission:</strong> <%= @car.transmission %></p>
     <p><strong>Price:</strong> £<%= @car.price %></p>
     <div data-controller="description-toggle" class="car-description">
     <button data-action="click->description-toggle#show" class="description-toggle">Description:</button>
     <ul data-description-toggle-target="details" class="additionl-details d-none">
      <% @car.car_description.split(',').each do |description| %>
       <li><%= description.strip %></li>
      <% end %>
     </ul>
    </div>
   </div>
  </div>
  <div class="rental-form-container">
   <h2>Rental Request Form</h1>
   <%= simple_form_for([@car, @rental], html: { class: "rental-form" }) do |f| %>
    <div class="form-group">
     <%= f.label :start_date, "Start Date" %>
     <%= f.input :start_date, label: false, input_html: { class: "form-control" } %>
    </div>
    <div class="form-group">
     <%= f.label :end_date, "End Date" %>
     <%= f.input :end_date, label: false, input_html: { class: "form-control" } %>
    </div>
    <div class="form-group">
     <%= f.button :submit, "Submit", class: "btn btn-light" %>
    </div>
   <% end %>
  </div>
  </div>
</div>
<div class="show-button">
  <%= link_to "View your bookings", dashboard_path, class: "btn btn-primary" %>
  <%= link_to "Go Back", cars_path, class: "btn btn-primary mx-4" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AutoGoGo</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <%= render "shared/navbar" %>
  <%= render "shared/flashes" %>
  <%= yield %>

  </body>
</html>

app/views/pages/dashboard.html.erb
<div class="container mt-5">
  <h1 class="mb-4">Welcome to Your Dashboard, <%= @user.name %></h1>

  <% if current_user %>
    <div class="row">
      <div class="col-md-6">
        <div class="card">
          <div class="card-header">
            <h2 class="card-title">Your Rentals</h2>
          </div>
          <ul class="list-group list-group-flush">
            <% @rentals.each do |rental| %>
              <li class="list-group-item">
                Rental ID: <%= rental.id %><br>
                Car: <%= rental.car.name %><br>
                Start Date: <%= rental.start_date %><br>
                End Date: <%= rental.end_date %>
              </li>
            <% end %>
          </ul>
        </div>
      </div>
      <div class="col-md-6">
        <div class="card">
          <div class="card-header">
            <h2 class="card-title">Your Cars</h2>
          </div>
          <ul class="list-group list-group-flush">
            <% @cars.each do |car| %>
              <li class="list-group-item">
                Car ID: <%= car.id %><br>
                Name: <%= car.name %><br>
                Type: <%= car.car_type %><br>
                Transmission: <%= car.transmission %><br>
                Price: £<%= car.price %>
              </li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
  <% else %>
    <% redirect_to root_path %>
  <% end %>
</div>

<style>
  .container {
    position: absolute;
    top: 80px;
    left: 0;
    right: 0;
    margin: 0 auto;
  }
</style>

app/views/pages/home.html.erb
    <div class="banner">

       <h3>Drive Your Dreams: Rent With Us Today!</h3>
    </div>


    <div class="search-bar">

      <div>
        <input type="text" placeholder="Explore cars...">
        <button>Search</button>
      </div>
      <div class="all-cars">
         <div class="description">
            <ul>
              <li>Join our vibrant community of travelers and car owners alike! </li>
              <li>With our unique car rental platform, it's easier than ever to share your wheels or find the perfect ride for your next journey.</li>
              <li>Owners, showcase your vehicle and earn extra income by listing it on our user-friendly website.</li>
              <li>Travelers, explore a diverse range of vehicles suited to your needs, preferences, and budget.</li>
            </ul>
            <%= link_to "See all cars", cars_path, class: "button-style" %>
        </div>


      </div>
    </div>
    <footer>
      <p>&copy; 2024 AutoGoGo. All rights reserved.</p>
    </footer>

    </body>
</html>

app/views/rentals/create.html.erb
<h1>Rentals#create</h1>
<p>Find me in app/views/rentals/create.html.erb</p>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">

  <div class="container-fluid">
    <%= link_to "#", class: "navbar-brand" do %>
      <%= image_tag "logo.jpg" %>
    <% end %>
      <div class='title'>
        <h1>AutoGoGo </h1>
      </div>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">

      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", root_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "List your car", new_car_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Dashboard", dashboard_path, class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
          <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= image_tag "logo.jpg", class: "avatar", alt: "dropdown menu" %>
          </a>

            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Action", "#", class: "dropdown-item" %>
              <%= link_to "Another action", "#", class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>

  </div>
</div>